services:
  - type: web
    name: go-url-shortener
    env: go
    plan: free
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    autoDeploy: true

  - type: web
    name: text-moderation-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
